config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  get 'charts/columnchart'
  get 'charts/barchart'
  get 'startup/index'
  post '/signup',  to: 'users#create'
  
  root 'startup#index'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :customers
  resources :pokemonatkvalues
  resources :pokemons
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pokemonatkvalue.rb
class Pokemonatkvalue < ApplicationRecord
  belongs_to :pokemon
end

app/controllers/pokemonatkvalues_controller.rb
class PokemonatkvaluesController < ApplicationController
  before_action :set_pokemonatkvalue, only: [:show, :edit, :update, :destroy]

  # GET /pokemonatkvalues
  # GET /pokemonatkvalues.json
  def index
    @pokemonatkvalues = Pokemonatkvalue.all
  end

  # GET /pokemonatkvalues/1
  # GET /pokemonatkvalues/1.json
  def show
  end

  # GET /pokemonatkvalues/new
  def new
    @pokemonatkvalue = Pokemonatkvalue.new
  end

  # GET /pokemonatkvalues/1/edit
  def edit
  end

  # POST /pokemonatkvalues
  # POST /pokemonatkvalues.json
  def create
    @pokemonatkvalue = Pokemonatkvalue.new(pokemonatkvalue_params)

    respond_to do |format|
      if @pokemonatkvalue.save
        format.html { redirect_to @pokemonatkvalue, notice: 'Pokemonatkvalue was successfully created.' }
        format.json { render :show, status: :created, location: @pokemonatkvalue }
      else
        format.html { render :new }
        format.json { render json: @pokemonatkvalue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemonatkvalues/1
  # PATCH/PUT /pokemonatkvalues/1.json
  def update
    respond_to do |format|
      if @pokemonatkvalue.update(pokemonatkvalue_params)
        format.html { redirect_to @pokemonatkvalue, notice: 'Pokemonatkvalue was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemonatkvalue }
      else
        format.html { render :edit }
        format.json { render json: @pokemonatkvalue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemonatkvalues/1
  # DELETE /pokemonatkvalues/1.json
  def destroy
    @pokemonatkvalue.destroy
    respond_to do |format|
      format.html { redirect_to pokemonatkvalues_url, notice: 'Pokemonatkvalue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemonatkvalue
      @pokemonatkvalue = Pokemonatkvalue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemonatkvalue_params
      params.require(:pokemonatkvalue).permit(:attack, :pokemon_id)
    end
end

app/helpers/pokemonatkvalues_helper.rb
module PokemonatkvaluesHelper
end

app/views/pokemonatkvalues/_form.html.erb
<%= form_with(model: pokemonatkvalue, local: true) do |form| %>
  <% if pokemonatkvalue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemonatkvalue.errors.count, "error") %> prohibited this pokemonatkvalue from being saved:</h2>

      <ul>
      <% pokemonatkvalue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :attack %>
    <%= form.number_field :attack, id: :pokemonatkvalue_attack %>
  </div>

  <div class="field">
    <%= form.label :pokemon_id %>
    <%= form.number_field :pokemon_id, id: :pokemonatkvalue_pokemon_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemonatkvalues/edit.html.erb
<h1>Editing Pokemonatkvalue</h1>

<%= render 'form', pokemonatkvalue: @pokemonatkvalue %>

<%= link_to 'Show', @pokemonatkvalue %> |
<%= link_to 'Back', pokemonatkvalues_path %>

app/views/pokemonatkvalues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pokemonatkvalues</h1>

<table>
  <thead>
    <tr>
      <th>Attack</th>
      <th>Pokemon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemonatkvalues.each do |pokemonatkvalue| %>
      <tr>
        <td><%= pokemonatkvalue.attack %></td>
        <td><%= pokemonatkvalue.pokemon_id %></td>
        <td><%= link_to 'Show', pokemonatkvalue %></td>
        <td><%= link_to 'Edit', edit_pokemonatkvalue_path(pokemonatkvalue) %></td>
        <td><%= link_to 'Destroy', pokemonatkvalue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pokemonatkvalue', new_pokemonatkvalue_path %>

app/views/pokemonatkvalues/new.html.erb
<h1>New Pokemonatkvalue</h1>

<%= render 'form', pokemonatkvalue: @pokemonatkvalue %>

<%= link_to 'Back', pokemonatkvalues_path %>

app/views/pokemonatkvalues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Attack:</strong>
  <%= @pokemonatkvalue.attack %>
</p>

<p>
  <strong>Pokemon:</strong>
  <%= @pokemonatkvalue.pokemon_id %>
</p>

<%= link_to 'Edit', edit_pokemonatkvalue_path(@pokemonatkvalue) %> |
<%= link_to 'Back', pokemonatkvalues_path %>