config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  get 'charts/columnchart'
  get 'charts/barchart'
  get 'startup/index'
  post '/signup',  to: 'users#create'
  
  root 'startup#index'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :customers
  resources :pokemonatkvalues
  resources :pokemons
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_one :pokemonatkvalue
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /pokemons
  # GET /pokemons.json
  def index
    @pokemons = Pokemon.all
  end
  
  def index
    @pokemons = if params[:name]
      Pokemon.where('name LIKE ?', "%#{params[:name]}%")
  else
    Pokemon.all
  end
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.permit(:name, :affinity)
    end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/_form.html.erb
<%= form_with(model: pokemon, local: true) do |form| %>
  <% if pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pokemon_name %>
  </div>

  <div class="field">
    <%= form.label :affinity %>
    <%= form.text_field :affinity, id: :pokemon_affinity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pokemons</h1>

<%= form_tag(pokemons_path, method: :get) do %>
  <%= text_field_tag :name, params[:name] %>
  <%= submit_tag 'Search' %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Affinity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>
        <td><%= pokemon.name %></td>
        <td><%= pokemon.affinity %></td>
        <td><%= link_to 'Show', pokemon %></td>
        <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
        <td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pokemon', new_pokemon_path %>

app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pokemon.name %>
</p>

<p>
  <strong>Affinity:</strong>
  <%= @pokemon.affinity %>
</p>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>