config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  get 'charts/columnchart'
  get 'charts/barchart'
  get 'startup/index'
  post '/signup',  to: 'users#create'
  
  root 'startup#index'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :customers
  resources :pokemonatkvalues
  resources :pokemons
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_one :pokemonatkvalue
end

app/models/pokemonatkvalue.rb
class Pokemonatkvalue < ApplicationRecord
  belongs_to :pokemon
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 225 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def columnchart
  end
  
  def barchart
  end  
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /pokemons
  # GET /pokemons.json
  def index
    @pokemons = Pokemon.all
  end
  
  def index
    @pokemons = if params[:name]
      Pokemon.where('name LIKE ?', "%#{params[:name]}%")
  else
    Pokemon.all
  end
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.permit(:name, :affinity)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
        user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
          params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
  else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/startup_controller.rb
class StartupController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)    
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Pokedex"
     redirect_to @user
    else
      render 'new'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/pokemonatkvalues_helper.rb
module PokemonatkvaluesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  
  def log_in(user)
    session[:user_id] = user.id
  end
  
    def remember(user)
      user.remember
      cookies.permanent.signed[:user_id] = user.id
      cookies.permanent[:remember_token] = user.remember_token
    end
    
  def current_user?(user)
    user == current_user
  end
  
    def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
    end
    
    def logged_in?
      !current_user.nil?
    end
    
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
    
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

app/helpers/startup_helper.rb
module StartupHelper
end

app/helpers/users_helper.rb
module UsersHelper

  
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
     <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-grayscale/css/grayscale.min.css" rel="stylesheet">
  </head>

  <body>
    
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    
   
    
    
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-left" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="/startup/index">Home</a>
        <a class="navbar-brand js-scroll-trigger" href="/pokemons">Pokemons</a>
        <a class="navbar-brand js-scroll-trigger" href="/login">Login</a>
        
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
           
            
             
            </li>
          </ul>
        </div>
      </div>
      </div>
    </nav>
    
    <%= yield %>
    
    <!-- Footer -->
    <footer>
    </div>
      <div class="container text-center">
       
      </div>
    </footer>
  </body>
</html>

app/views/layouts/application.html_BACKUP_3950.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
     <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-grayscale/css/grayscale.min.css" rel="stylesheet">
  </head>

  <body>
    
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    
   
    
    
    <!-- Navigation -->
    
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
           
            
             
            </li>
          </ul>
        </div>
      </div>
      </div>
    </nav>
    
    <%= yield %>
    
    <!-- Footer -->
    <footer>
    </div>
      <div class="container text-center">
       
      </div>
    </footer>
  </body>
</html>

app/views/layouts/application.html_BASE_3950.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
     <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-grayscale/css/grayscale.min.css" rel="stylesheet">
  </head>

  <body>
    
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    
   
    
    
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-left" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="https://pokemon-pracoro.c9users.io/startup/index">Home</a>
        
        
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
           
            
             
            </li>
          </ul>
        </div>
      </div>
      </div>
    </nav>
    
    <%= yield %>
    
    <!-- Footer -->
    <footer>
    </div>
      <div class="container text-center">
       
      </div>
    </footer>
  </body>
</html>

app/views/layouts/application.html_LOCAL_3950.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
     <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-grayscale/css/grayscale.min.css" rel="stylesheet">
  </head>

  <body>
    
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    
   
    
    
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-left" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="https://pokemon-pracoro.c9users.io/startup/index">Home</a>
        <a class="navbar-brand js-scroll-trigger" href="https://pokemon-pracoro.c9users.io/pokemons">Pokemons</a>
        <a class="navbar-brand js-scroll-trigger" href="https://pokemon-pracoro.c9users.io/login">Login</a>
        
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
           
            
             
            </li>
          </ul>
        </div>
      </div>
      </div>
    </nav>
    
    <%= yield %>
    
    <!-- Footer -->
    <footer>
    </div>
      <div class="container text-center">
       
      </div>
    </footer>
  </body>
</html>

app/views/layouts/application.html_REMOTE_3950.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
     <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-grayscale/css/grayscale.min.css" rel="stylesheet">
  </head>

  <body>
    
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    
   
    
    
    <!-- Navigation -->
    
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", href="https://pokemon-pracoro.c9users.io/startup/index" %></li>
            <li><%= link_to "Help",   '#' %></li>
            <li><%= link_to "Log in", '#' %></li>
          </ul>
        
        
        
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
           
            
             
            </li>
          </ul>
        </div>
      </div>
      </div>
    </nav>
    
    <%= yield %>
    
    <!-- Footer -->
    <footer>
    </div>
      <div class="container text-center">
       
      </div>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>